site_name: TeSLA Plagiarism Tools base on URKUND
site_url: https://tesla-ce.github.io/provider-pt-urkund/
site_author: Roger Munoz

nav:
    - Home: index.md
    - Options: options.md

theme:
  name: "material"
  custom_dir: overrides

markdown_extensions:
  - admonition

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          load_external_modules: true
          allow_inspection: true
          options:
            rendering:
              show_source: true
            selection:
              docstring_style: sphinx
extra:
  version:
    provider: mike

