version: '3.5'
services:
  urkund_provider:
    image: teslace/provider-pt-urkund:edge
    healthcheck:
      test: /venv/bin/celery -A tesla_ce_provider inspect ping || exit 1
      interval: 60s
      timeout: 60s
      retries: 3
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
    environment:
      ROLE_ID_FILE: "/run/secrets/ROLE_ID"
      SECRET_ID_FILE: "/run/secrets/SECRET_ID"
      URKUND_USER: URKUND_USER
      URKUND_PASSWORD: URKUND_PASSWORD
      URKUND_ORGANIZATION: URKUND_ORGANIZATION
      URKUND_SUBORGANIZATION: URKUND_SUBORGANIZATION
      URKUND_UNIT: URKUND_UNIT
      URKUND_DEFAULT_EMAIL_RECEIVER: URKUND_DEFAULT_EMAIL_RECEIVER@tesla-ce.eu
      API_URL: https://demo.tesla-project.eu
      VERIFY_SSL: 0
      SENTRY_ENABLED: 1
      SENTRY_DSN: https://4bd3a90ef4e443dba70e7fa41aa5cfd6@sentry.sunai.uoc.edu/11
      LOG_TASK_TRACE: 1
    secrets:
      - source: URKUND_ROLE_ID
        target: ROLE_ID
      - source: URKUND_SECRET_ID
        target: SECRET_ID

secrets:
  URKUND_ROLE_ID:
    file: ./secrets/URKUND_ROLE_ID
  URKUND_SECRET_ID:
    file: ./secrets/URKUND_SECRET_ID

networks:
  tesla_public:
    external: true
  tesla_private:
    external: true
