version: '3.5'
services:
  urkund_provider:
    image: teslace/provider-pt-urkund:edge
    healthcheck:
      test: /venv/bin/celery -A tesla_ce_provider inspect ping || exit 1
      interval: 60s
      timeout: 60s
      retries: 3
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
    environment:
      ROLE_ID_FILE: "/run/secrets/ROLE_ID"
      SECRET_ID_FILE: "/run/secrets/SECRET_ID"
      URKUND_USER_FILE: "/run/secrets/URKUND_USER"
      URKUND_PASSWORD_FILE: "/run/secrets/URKUND_PASSWORD"
      URKUND_ORGANIZATION_FILE: "/run/secrets/URKUND_ORGANIZATION"
      URKUND_SUBORGANIZATION_FILE: "/run/secrets/URKUND_SUBORGANIZATION"
      URKUND_UNIT_FILE: "/run/secrets/URKUND_UNIT"
      URKUND_DEFAULT_EMAIL_RECEIVER_FILE: "/run/secrets/URKUND_DEFAULT_EMAIL_RECEIVER"
      API_URL: https://demo.tesla-project.eu
      VERIFY_SSL: 0
      SENTRY_ENABLED: 1
      SENTRY_DSN: https://4bd3a90ef4e443dba70e7fa41aa5cfd6@sentry.sunai.uoc.edu/11
      LOG_TASK_TRACE: 1
    secrets:
      - source: URKUND_ROLE_ID
        target: ROLE_ID
      - source: URKUND_SECRET_ID
        target: SECRET_ID
      - source: URKUND_USER
        target: URKUND_USER
      - source: URKUND_PASSWORD
        target: URKUND_PASSWORD
      - source: URKUND_ORGANIZATION
        target: URKUND_ORGANIZATION
      - source: URKUND_SUBORGANIZATION
        target: URKUND_SUBORGANIZATION
      - source: URKUND_UNIT
        target: URKUND_UNIT
      - source: URKUND_DEFAULT_EMAIL_RECEIVER
        target: URKUND_DEFAULT_EMAIL_RECEIVER
secrets:
  URKUND_ROLE_ID:
    file: ./secrets/URKUND_ROLE_ID
  URKUND_SECRET_ID:
    file: ./secrets/URKUND_SECRET_ID
  URKUND_USER:
    file: ./secrets/URKUND_USER
  URKUND_PASSWORD:
    file: ./secrets/URKUND_PASSWORD
  URKUND_ORGANIZATION:
    file: ./secrets/URKUND_ORGANIZATION
  URKUND_SUBORGANIZATION:
    file: ./secrets/URKUND_SUBORGANIZATION
  URKUND_UNIT:
    file: ./secrets/URKUND_UNIT
  URKUND_DEFAULT_EMAIL_RECEIVER:
    file: ./secrets/URKUND_DEFAULT_EMAIL_RECEIVER
networks:
  tesla_public:
    external: true
  tesla_private:
    external: true
